project:
  type: website
  output-dir: _site

website:
  title: "Vicente Abrigo"
  navbar:
    right:
      - href: index.qmd
        text: Inicio

format:
  html:
    theme: cosmo
    toc: true

editor: visual